name: 'Release to Keygen'
description: 'Create a release and upload associated artifact'
author: 'hfend'
inputs:
  account-id:
    required: true
    description: 'Account ID'
  token:
    required: true
    description: 'Token'

  product-id:
    required: true
    description: 'Product ID'

  release-publish:
    required: true
    description: 'Publish release (true / false)?'
  
  release-name:
    required: false
    description: 'Release Name'
  release-version:
    required: true
    description: 'Release version'
  release-channel:
    required: true
    description: 'Release channel'
  release-tag:
    required: false
    description: 'Release tag'

  artifacts-json:
    required: true
    description: 'A json string of a list of artifact definitions'
runs:
  using: 'node16'
  main: 'dist/index.js'
